In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# import sklearn libraries
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans

In [2]:
#data_path = os.path.join("Titanic", "train.csv")
data_path = "Lead_Scoring.csv"
#data_path = r"Titanic\train.csv"
print(data_path)

Lead_Scoring.csv

In [3]:
data = pd.read_csv(data_path)

In [4]:
data.shape #(baris, kolom)

(9240, 37)

# Keterangan Data

1. Prospect ID : A unique ID with which the customer is identified.
2. Lead Number : A lead number assigned to each lead procured.
3. Lead Origin : The origin identifier with which the customer was identified to be a lead. Includes API, Landing Page Submission, etc.
4. Lead Source : The source of the lead. Includes Google, Organic Search, Olark Chat, etc.
5. Do Not Email : An indicator variable selected by the customer wherein they select whether of not they want to be emailed about the course or not.
6. Do Not Call : An indicator variable selected by the customer wherein they select whether of not they want to be called about the course or not.
7. Converted : The target variable. Indicates whether a lead has been successfully converted or not.
8. TotalVisits : The total number of visits made by the customer on the website.
9. Total Time Spent on Website : The total time spent by the customer on the website.
10. Page Views Per Visit : Average number of pages on the website viewed during the visits.
11. Last Activity : Last activity performed by the customer. Includes Email Opened, Olark Chat Conversation, etc.
12. Country : The country of the customer.
13. Specialization : The industry domain in which the customer worked before. Includes the level 'Select Specialization' which means the customer had not selected this option while filling the form.
14. How did you hear about Madugital : The source from which the customer heard about Madugital.
15. What is your current occupation : Indicates whether the customer is a student, unemployed or employed.
16. What matters most to you in choosing this product : An option selected by the customer indicating what is their main motto behind buying this product.
17. Search : Indicating whether the customer had seen the ad in any of the listed items.
18. Magazine : Indicating whether the customer had seen the ad in any of the listed items.
19. Newspaper Article : Indicating whether the customer had seen the ad in any of the listed items.
20. Madugital Forum Indicating whether the customer had seen the ad in any of the listed items.
21. Newspaper : Indicating whether the customer had seen the ad in any of the listed items.
22. Digital Advertisement : Indicating whether the customer had seen the ad in any of the listed items.
23. Through Recommendations : Indicates whether the customer came in through recommendations.
24. Receive More Updates About Our Courses : Indicates whether the customer chose to receive more updates about the courses.
25. Tags : Tags assigned to customers indicating the current status of the lead.
26. Lead Quality : Indicates the quality of lead based on the data and intuition the the employee who has been assigned to the lead.
27. Update me on Supply Chain Content : Indicates whether the customer wants updates on the Supply Chain Content.
28. Get updates on DM Content : Indicates whether the customer wants updates on the DM Content.
29. Lead Profile : A lead level assigned to each customer based on their profile.
30. City : The city of the customer.
31. Asymmetrique Activity Index : An index and score assigned to each customer based on their activity and their profile
32. Asymmetrique Profile Index :An index and score assigned to each customer based on their activity and their profile
33. Asymmetrique Activity Score :An index and score assigned to each customer based on their activity and their profile
34. Asymmetrique Profile Score : An index and score assigned to each customer based on their activity and their profile
35. I agree to pay the amount through cheque : Indicates whether the customer has agreed to pay the amount through cheque or not.
36. a free copy of Mastering The Healthy Live : Indicates whether the customer wants a free copy of 'Mastering the Healthy Live' or not.
37. Last Notable Activity : The last notable acitivity performed by the customer.

In [5]:
data.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Jakarta,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Jakarta,02.Medium,01.High,15.0,18.0,No,No,Modified

In [6]:
data.tail()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Jakarta,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [7]:
data.sample(5, random_state=91)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
6936,2154ccbd-41f9-46f0-9edb-308cde9fc52d,596447,Landing Page Submission,Google,No,No,0,2.0,238,2.0,...,No,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,Modified
2140,5f05a482-8fb5-4fe8-aca3-0f7b9d794178,639211,Lead Add Form,Reference,No,No,1,0.0,0,0.0,...,No,Potential Lead,Bodetabek,02.Medium,02.Medium,14.0,16.0,No,No,Modified
4377,2be87f90-5931-49dc-bb87-54d8452cb693,617791,Landing Page Submission,Google,No,No,0,5.0,582,5.0,...,No,Select,Jakarta,NaN,NaN,NaN,NaN,No,No,SMS Sent
5208,65e13a16-f5c0-49a1-8187-a4795a5941fb,609879,Landing Page Submission,Direct Traffic,No,No,0,3.0,1686,3.0,...,No,Select,Bodetabek,NaN,NaN,NaN,NaN,No,Yes,Email Opened
1041,0adb324b-c2a3-4880-a928-6e1589914ab4,649091,Landing Page Submission,Google,No,No,0,7.0,1541,3.5,...,No,NaN,Cities in Banten & Jawa Barat,02.Medium,01.High,14.0,17.0,No,Yes,Email Opened

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Prospect ID                                     9240 non-null   object
 1   Lead Number                                     9240 non-null   int64
 2   Lead Origin                                     9240 non-null   object
 3   Lead Source                                     9204 non-null   object
 4   Do Not Email                                    9240 non-null   object
 5   Do Not Call                                     9240 non-null   object
 6   Converted                                       9240 non-null   int64
 7   TotalVisits                                     9103 non-null   float64
 8   Total Time Spent on Website                     9240 non-null   int64
 9   Page Views Per Visit                            9103 non-null   float64
 10  Last Activity                                   9137 non-null   object
 11  Country                                         6779 non-null   object
 12  Specialization                                  7802 non-null   object
 13  How did you hear about Madugital                7033 non-null   object
 14  What is your current occupation                 6550 non-null   object
 15  What matters most to you in choosing a product  6531 non-null   object
 16  Search                                          9240 non-null   object
 17  Magazine                                        9240 non-null   object
 18  Newspaper Article                               9240 non-null   object
 19  Madugital Telegram                              9240 non-null   object
 20  Newspaper                                       9240 non-null   object
 21  Digital Advertisement                           9240 non-null   object
 22  Through Recommendations                         9240 non-null   object
 23  Receive More Updates About Our Products         9240 non-null   object
 24  Tags                                            5887 non-null   object
 25  Lead Quality                                    4473 non-null   object
 26  Update me on Supply Chain Content               9240 non-null   object
 27  Get updates on DM Content                       9240 non-null   object
 28  Lead Profile                                    6531 non-null   object
 29  City                                            7820 non-null   object
 30  Asymmetrique Activity Index                     5022 non-null   object
 31  Asymmetrique Profile Index                      5022 non-null   object
 32  Asymmetrique Activity Score                     5022 non-null   float64
 33  Asymmetrique Profile Score                      5022 non-null   float64
 34  I agree to pay the amount through cheque        9240 non-null   object
 35  A free copy of Mastering The Interview          9240 non-null   object
 36  Last Notable Activity                           9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 1.6+ MB

In [9]:
data["Receive More Updates About Our Products"].unique()

array(['No'], dtype=object)

In [10]:
#data.describe() # untuk data numeric

data.describe(include=['O']) # untuk data categoric

,Prospect ID,Lead Origin,Lead Source,Do Not Email,Do Not Call,Last Activity,Country,Specialization,How did you hear about Madugital,What is your current occupation,...,Lead Quality,Update me on Supply Chain Content,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
count,9240,9240,9204,9240,9240,9137,6779,7802,7033,6550,...,4473,9240,9240,6531,7820,5022,5022,9240,9240,9240
unique,9240,5,21,2,2,17,38,19,10,6,...,5,1,1,6,7,3,3,1,2,16
top,8f9a5c4a-c627-436f-9ada-3d5675e6afa0,Landing Page Submission,Google,No,No,Email Opened,Indonesia,Select,Select,Unemployed,...,Might be,No,No,Select,Jakarta,02.Medium,02.Medium,No,No,Modified
freq,1,4886,2868,8506,9238,3437,6492,1942,5043,5600,...,1560,9240,9240,4146,3222,3839,2788,9240,6352,3407

In [11]:
data.isnull().sum()

Prospect ID                                          0
Lead Number                                          0
Lead Origin                                          0
Lead Source                                         36
Do Not Email                                         0
Do Not Call                                          0
Converted                                            0
TotalVisits                                        137
Total Time Spent on Website                          0
Page Views Per Visit                               137
Last Activity                                      103
Country                                           2461
Specialization                                    1438
How did you hear about Madugital                  2207
What is your current occupation                   2690
What matters most to you in choosing a product    2709
Search                                               0
Magazine                                             0
Newspaper Article                                    0
Madugital Telegram                                   0
Newspaper                                            0
Digital Advertisement                                0
Through Recommendations                              0
Receive More Updates About Our Products              0
Tags                                              3353
Lead Quality                                      4767
Update me on Supply Chain Content                    0
Get updates on DM Content                            0
Lead Profile                                      2709
City                                              1420
Asymmetrique Activity Index                       4218
Asymmetrique Profile Index                        4218
Asymmetrique Activity Score                       4218
Asymmetrique Profile Score                        4218
I agree to pay the amount through cheque             0
A free copy of Mastering The Interview               0
Last Notable Activity                                0
dtype: int64

In [12]:
data.isna().mean() * 100

Prospect ID                                        0.000000
Lead Number                                        0.000000
Lead Origin                                        0.000000
Lead Source                                        0.389610
Do Not Email                                       0.000000
Do Not Call                                        0.000000
Converted                                          0.000000
TotalVisits                                        1.482684
Total Time Spent on Website                        0.000000
Page Views Per Visit                               1.482684
Last Activity                                      1.114719
Country                                           26.634199
Specialization                                    15.562771
How did you hear about Madugital                  23.885281
What is your current occupation                   29.112554
What matters most to you in choosing a product    29.318182
Search                                             0.000000
Magazine                                           0.000000
Newspaper Article                                  0.000000
Madugital Telegram                                 0.000000
Newspaper                                          0.000000
Digital Advertisement                              0.000000
Through Recommendations                            0.000000
Receive More Updates About Our Products            0.000000
Tags                                              36.287879
Lead Quality                                      51.590909
Update me on Supply Chain Content                  0.000000
Get updates on DM Content                          0.000000
Lead Profile                                      29.318182
City                                              15.367965
Asymmetrique Activity Index                       45.649351
Asymmetrique Profile Index                        45.649351
Asymmetrique Activity Score                       45.649351
Asymmetrique Profile Score                        45.649351
I agree to pay the amount through cheque           0.000000
A free copy of Mastering The Interview             0.000000
Last Notable Activity                              0.000000
dtype: float64

In [13]:
data_dropped = data.dropna()
data_dropped.isnull().sum()

Prospect ID                                       0
Lead Number                                       0
Lead Origin                                       0
Lead Source                                       0
Do Not Email                                      0
Do Not Call                                       0
Converted                                         0
TotalVisits                                       0
Total Time Spent on Website                       0
Page Views Per Visit                              0
Last Activity                                     0
Country                                           0
Specialization                                    0
How did you hear about Madugital                  0
What is your current occupation                   0
What matters most to you in choosing a product    0
Search                                            0
Magazine                                          0
Newspaper Article                                 0
Madugital Telegram                                0
Newspaper                                         0
Digital Advertisement                             0
Through Recommendations                           0
Receive More Updates About Our Products           0
Tags                                              0
Lead Quality                                      0
Update me on Supply Chain Content                 0
Get updates on DM Content                         0
Lead Profile                                      0
City                                              0
Asymmetrique Activity Index                       0
Asymmetrique Profile Index                        0
Asymmetrique Activity Score                       0
Asymmetrique Profile Score                        0
I agree to pay the amount through cheque          0
A free copy of Mastering The Interview            0
Last Notable Activity                             0
dtype: int64

In [14]:
data.shape, data_dropped.shape

((9240, 37), (1943, 37))

In [15]:
data_dropped = data.drop(columns=['Lead Quality'], axis=1)
data_dropped.isnull().sum()

Prospect ID                                          0
Lead Number                                          0
Lead Origin                                          0
Lead Source                                         36
Do Not Email                                         0
Do Not Call                                          0
Converted                                            0
TotalVisits                                        137
Total Time Spent on Website                          0
Page Views Per Visit                               137
Last Activity                                      103
Country                                           2461
Specialization                                    1438
How did you hear about Madugital                  2207
What is your current occupation                   2690
What matters most to you in choosing a product    2709
Search                                               0
Magazine                                             0
Newspaper Article                                    0
Madugital Telegram                                   0
Newspaper                                            0
Digital Advertisement                                0
Through Recommendations                              0
Receive More Updates About Our Products              0
Tags                                              3353
Update me on Supply Chain Content                    0
Get updates on DM Content                            0
Lead Profile                                      2709
City                                              1420
Asymmetrique Activity Index                       4218
Asymmetrique Profile Index                        4218
Asymmetrique Activity Score                       4218
Asymmetrique Profile Score                        4218
I agree to pay the amount through cheque             0
A free copy of Mastering The Interview               0
Last Notable Activity                                0
dtype: int64

In [16]:
data.shape, data_dropped.shape

((9240, 37), (9240, 36))

In [17]:
data_dropped['Specialization'] = data_dropped['Specialization'].fillna('Missing')
data_dropped['City'] = data_dropped['City'].fillna('Missing')
data_dropped['Tags'] = data_dropped['Tags'].fillna('Missing')
data_dropped['What matters most to you in choosing a product'] = data_dropped['What matters most to you in choosing a product'].fillna('Missing')
data_dropped['What is your current occupation'] = data_dropped['What is your current occupation'].fillna('Missing')
data_dropped['How did you hear about Madugital'] = data_dropped['How did you hear about Madugital'].fillna('Missing')
data_dropped['Country'] = data_dropped['Country'].fillna('Missing')

data_dropped['TotalVisits'] = data_dropped['TotalVisits'].fillna(data_dropped['TotalVisits'].mean())
data_dropped['Page Views Per Visit'] = data_dropped['Page Views Per Visit'].fillna(data_dropped['Page Views Per Visit'].mean())

data_dropped['Asymmetrique Activity Index'] = data_dropped['Asymmetrique Activity Index'].fillna(data_dropped['Asymmetrique Activity Index'].value_counts().idxmax())
data_dropped['Asymmetrique Profile Index'] = data_dropped['Asymmetrique Profile Index'].fillna(data_dropped['Asymmetrique Profile Index'].value_counts().idxmax())
data_dropped['Asymmetrique Activity Score'] = data_dropped['Asymmetrique Activity Score'].fillna(data_dropped['Asymmetrique Activity Score'].value_counts().idxmax())
data_dropped['Asymmetrique Profile Score'] = data_dropped['Asymmetrique Profile Score'].fillna(data_dropped['Asymmetrique Profile Score'].value_counts().idxmax())
data_dropped['Last Activity'] = data_dropped['Last Activity'].fillna(data_dropped['Last Activity'].value_counts().idxmax())
data_dropped['Lead Profile'] = data_dropped['Lead Profile'].fillna(data_dropped['Lead Profile'].value_counts().idxmax())

In [18]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 36 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Prospect ID                                     9240 non-null   object
 1   Lead Number                                     9240 non-null   int64
 2   Lead Origin                                     9240 non-null   object
 3   Lead Source                                     9204 non-null   object
 4   Do Not Email                                    9240 non-null   object
 5   Do Not Call                                     9240 non-null   object
 6   Converted                                       9240 non-null   int64
 7   TotalVisits                                     9240 non-null   float64
 8   Total Time Spent on Website                     9240 non-null   int64
 9   Page Views Per Visit                            9240 non-null   float64
 10  Last Activity                                   9240 non-null   object
 11  Country                                         9240 non-null   object
 12  Specialization                                  9240 non-null   object
 13  How did you hear about Madugital                9240 non-null   object
 14  What is your current occupation                 9240 non-null   object
 15  What matters most to you in choosing a product  9240 non-null   object
 16  Search                                          9240 non-null   object
 17  Magazine                                        9240 non-null   object
 18  Newspaper Article                               9240 non-null   object
 19  Madugital Telegram                              9240 non-null   object
 20  Newspaper                                       9240 non-null   object
 21  Digital Advertisement                           9240 non-null   object
 22  Through Recommendations                         9240 non-null   object
 23  Receive More Updates About Our Products         9240 non-null   object
 24  Tags                                            9240 non-null   object
 25  Update me on Supply Chain Content               9240 non-null   object
 26  Get updates on DM Content                       9240 non-null   object
 27  Lead Profile                                    9240 non-null   object
 28  City                                            9240 non-null   object
 29  Asymmetrique Activity Index                     9240 non-null   object
 30  Asymmetrique Profile Index                      9240 non-null   object
 31  Asymmetrique Activity Score                     9240 non-null   float64
 32  Asymmetrique Profile Score                      9240 non-null   float64
 33  I agree to pay the amount through cheque        9240 non-null   object
 34  A free copy of Mastering The Interview          9240 non-null   object
 35  Last Notable Activity                           9240 non-null   object
dtypes: float64(4), int64(3), object(29)
memory usage: 1.5+ MB

In [19]:
data = data.append(data.loc[1], ignore_index=True)

In [20]:
data.loc[data['Lead Number'].duplicated()]

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
9240,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened

In [21]:
data.drop_duplicates(keep=False)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,Select,Jakarta,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,Select,Jakarta,02.Medium,01.High,15.0,18.0,No,No,Modified
5,2058ef08-2858-443e-a01f-a9237db2f5ce,660680,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,NaN,NaN,01.High,02.Medium,17.0,15.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Jakarta,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Jakarta,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [22]:
data.groupby('Country').mean()[['Page Views Per Visit']]

                      Page Views Per Visit
Country
Asia/Pacific Region               1.000000
Australia                         3.769231
Bahrain                           2.571429
Bangladesh                        2.500000
Belgium                           3.000000
Canada                            2.832500
China                             1.500000
Denmark                           4.000000
France                            2.788333
Germany                           3.375000
Ghana                             2.000000
Hong Kong                         3.142857
India                             6.000000
Indonesia                         3.137768
Italy                             2.000000
Kenya                             2.000000
Kuwait                            2.500000
Liberia                           1.000000
Malaysia                          2.000000
Netherlands                       5.750000
Nigeria                           3.500000
Oman                              1.916667
Philippines                       2.500000
Qatar                             2.900000
Russia                            1.000000
Saudi Arabia                      2.825714
Singapore                         2.604167
South Africa                      2.042500
Sri Lanka                         5.000000
Sweden                            1.570000
Switzerland                       2.000000
Tanzania                          2.000000
Uganda                            2.000000
United Arab Emirates              3.333208
United Kingdom                    3.233333
United States                     2.348116
Vietnam                           2.000000
unknown                           6.600000

In [23]:
pd.crosstab(data['Country'], data['Receive More Updates About Our Products'], normalize=True) # normalize=True

Receive More Updates About Our Products        No
Country
Asia/Pacific Region                      0.000295
Australia                                0.001917
Bahrain                                  0.001032
Bangladesh                               0.000295
Belgium                                  0.000295
Canada                                   0.000590
China                                    0.000295
Denmark                                  0.000147
France                                   0.000885
Germany                                  0.000590
Ghana                                    0.000295
Hong Kong                                0.001032
India                                    0.000147
Indonesia                                0.957670
Italy                                    0.000295
Kenya                                    0.000147
Kuwait                                   0.000590
Liberia                                  0.000147
Malaysia                                 0.000147
Netherlands                              0.000295
Nigeria                                  0.000590
Oman                                     0.000885
Philippines                              0.000295
Qatar                                    0.001475
Russia                                   0.000147
Saudi Arabia                             0.003097
Singapore                                0.003540
South Africa                             0.000590
Sri Lanka                                0.000147
Sweden                                   0.000442
Switzerland                              0.000147
Tanzania                                 0.000147
Uganda                                   0.000295
United Arab Emirates                     0.007817
United Kingdom                           0.002212
United States                            0.010177
Vietnam                                  0.000147
unknown                                  0.000737

In [24]:
pd.qcut(data['TotalVisits'], 3)

0       (-0.001, 2.0]
1        (4.0, 251.0]
2       (-0.001, 2.0]
3       (-0.001, 2.0]
4       (-0.001, 2.0]
            ...
9236    (-0.001, 2.0]
9237    (-0.001, 2.0]
9238       (2.0, 4.0]
9239     (4.0, 251.0]
9240     (4.0, 251.0]
Name: TotalVisits, Length: 9241, dtype: category
Categories (3, interval[float64]): [(-0.001, 2.0] < (2.0, 4.0] < (4.0, 251.0]]

In [25]:
pd.qcut(data['TotalVisits'], 3).value_counts()

(-0.001, 2.0]    4264
(2.0, 4.0]       2426
(4.0, 251.0]     2414
Name: TotalVisits, dtype: int64

In [26]:
#data_dropped['Not Interest'] = np.where(data_dropped['TotalVisits']<2, 'Yes', 'No')

data_dropped['Satisfaction'] = np.where(data_dropped['TotalVisits']<2, 'Not Interest', 'So so')
data_dropped['Satisfaction'] = np.where(data_dropped['TotalVisits']>=6, 'Excelent', data_dropped['Satisfaction'])

In [27]:
data_dropped.sample(10)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity,Satisfaction
6055,39ce0dd3-7bcc-4c0f-8d70-57b225419021,603364,Landing Page Submission,Direct Traffic,No,No,0,2.0,1319,2.00,...,Select,Jakarta,02.Medium,02.Medium,14.0,15.0,No,Yes,Email Opened,So so
4882,fd36e518-2802-4f5f-af61-a25361df53c1,613178,API,Olark Chat,No,No,1,0.0,0,0.00,...,Other Leads,Jakarta,02.Medium,02.Medium,14.0,15.0,No,No,Modified,Not Interest
5796,ebc4e749-8230-49f9-856b-0d86173d54d1,605302,API,Olark Chat,No,No,0,0.0,0,0.00,...,Select,Select,02.Medium,02.Medium,14.0,15.0,No,No,Olark Chat Conversation,Not Interest
4185,d522a3d3-f0c6-4075-b802-79bee9ef91c7,619676,Landing Page Submission,Direct Traffic,No,No,1,8.0,489,8.00,...,Select,Jakarta,02.Medium,02.Medium,14.0,15.0,No,Yes,SMS Sent,Excelent
3397,406b18a4-e789-4e77-9168-93a058f210b4,627637,Landing Page Submission,Organic Search,No,No,0,3.0,145,3.00,...,Select,Jakarta,02.Medium,02.Medium,14.0,15.0,No,Yes,Modified,So so
4472,8e15cda0-2d35-428e-b237-babb60449861,616733,Landing Page Submission,Direct Traffic,No,No,1,9.0,1324,3.00,...,Select,Jakarta,02.Medium,02.Medium,14.0,15.0,No,Yes,Email Opened,Excelent
4948,47fef145-1490-428d-9918-6f157a3c2501,612572,API,Google,No,No,1,3.0,789,1.00,...,Select,Missing,02.Medium,02.Medium,14.0,15.0,No,No,SMS Sent,So so
805,856fd959-07ed-45f6-aa4b-32619994bd9d,651993,API,Olark Chat,No,No,1,0.0,0,0.00,...,Select,Select,02.Medium,02.Medium,14.0,15.0,No,No,SMS Sent,Not Interest
4215,70cae9c3-93c1-4a18-a471-7326c61721b4,619446,API,Google,Yes,No,0,5.0,1132,1.25,...,Select,Missing,02.Medium,02.Medium,14.0,15.0,No,No,Modified,So so
1054,8a77bc3f-65e9-494f-8141-d475eca13766,648987,API,Referral Sites,No,No,0,5.0,320,5.00,...,Select,Select,02.Medium,02.Medium,14.0,13.0,No,No,Modified,So so